pipeline {
    agent any
    tools{
        maven 'M3'
    }
    stages{
        stage('Build Maven'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/debashishbarua/hello-service.git']]])
                dir('hello-service'){
      	            bat 'mvn clean package'      
   		        } 
            }
        }
        stage('Build docker image'){
            steps{
                script{
                    dir('hello-service'){
                        bat 'docker build -t debashishbarua/devops-integration .'
                    }
                }
            }
        }
        stage('Push image to Hub'){
            steps{
                script{
                    dir('hello-service'){
                        withCredentials([string(credentialsId: 'dockerhub-pwd', variable: 'dockerhubpwd')]) {
                        bat 'docker login -u debashishbarua -p Spring30@2pi' }
                        bat 'docker push debashishbarua/devops-integration'
                    }
                   
                }
            }
        }
    }
}
