pipeline {
  agent any
  tools {
    maven 'M3' 
  }
  environment {
    DATE = new Date().format('yy.M')
    TAG = "${DATE}.${BUILD_NUMBER}"
  }
  stages {
   stage ('Build') {
     steps {
		dir('hello-service'){
      		bat 'mvn clean package'      
   		}        
     }
   }   
   stage('Docker Build') {
           steps {
                  docker.build("debashishbarua/hello-service:${TAG}")
                 
   			}      
   }  
   stage('Pushing Docker Image to Dockerhub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_credential') {
                        docker.image("debashishbarua/hello-service:${TAG}").push()
                        docker.image("debashishbarua/hello-service:${TAG}").push("latest")
                    }
                
            }
   }
   stage('Deploy'){
            steps {
                bat 'docker stop hello-world | true'
                bat 'docker rm hello-world | true'
				bat 'docker run --name hello-service -d -p 9090:9090 debashishbarua/hello-service:${TAG}'            }
        }
    }
 }
}